development:
  adapter: postgresql
  encoding: unicode
  database: molawson_development
  pool: 5
  username: molawson
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: molawson_test
  pool: 5
  username: molawson
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: molawson_production
  pool: 5
  username: molawson
  password:
